### ISSUE TITLE
[BUG] HTTP Worker does not process request

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/issues#11]
**Describe the bug**
 I have a wired problem with my cluster: https://console.cloud.camunda.io/cluster/5ef1653d-27e9-42df-9c4b-8a269d565fac
You can see it with this workflow instance: https://5ef1653d-27e9-42df-9c4b-8a269d565fac.operate.camunda.io/#/instances/2251799813685733
This code base: https://github.com/berndruecker/trip-booking-saga-serverless/tree/master/zeebe/aws
The workflow hangs without any incident at the second Lambda call forever. The first one succeeds - and there is no difference in what I do. I can't see any feedback or logs.

**To Reproduce**
See readme. Deploy the functions and the workflow and run it.
Possibly also able to reproduce in a stripped down manner - have not tried yet.

**Expected behavior**
The HTTP should process my tasks.

**Scenario**
See above

![grafik](https://user-images.githubusercontent.com/1217596/81057036-f64d7c80-8ecb-11ea-9bea-0fc7c1ca56bd.png)

**Comment by ColRad** [comment]
I suspect it might be because of a bug in the serverless car/book implementation: https://github.com/berndruecker/trip-booking-saga-serverless/blob/77a390fe7e47939c8e0e4e8dcf382ff8757ce8a7/functions/aws/car/book/index.js#L24
AFAIK this is not implemented in the way AWS lambdas expect callbacks.

This should look like this:
```
callback(null, {
    statusCode: 200,
    body: responseBody
  });
```

**Comment by berndruecker** [comment]
Thanks @ColRad - that was the real problem. Fixed.
